user.js
- removed the 'period' at the end of the pref description (we usually don't have one there)
- re-aligned the 2nd line of 'the downside'
=> network.IDN_show_punycode

user.js
added inactive under 3000: PERSONAL SETTINGS
=> add accessibility.typeaheadfind

user.js
inactive as per proposal (C) @ https://github.com/ghacksuserjs/ghacks-user.js/issues/24#issue-209476365
=> add static-rsa prefs

user.js
both @atomGit and myself are using 150 - not a biggie, lets just do it
=> ui.submenuDelay

updater.bat
@earthlng My first time using GitHub for something other than reporting stuff. I hope I'm not messing up somehow 😓
=> Just some polishing

updater.sh
... at fixing the script path detection. should hopefully fix https://github.com/ghacksuserjs/ghacks-user.js/issues/264#issuecomment-346891526
=> updater.sh - next attempt

updater.bat
=> updater.bat auto-update part

updater.bat
FIxed `-updatebatch` switch, which is now case-insensitive too.
Other fixes below. Don't be lazy and just read the commit notes.
There's more to come, but you can merge this in the meantime if you want (or ditch it). Up to you.
@earthlng Thanks again for your help testing and ironing out my initial mess, and for the fancy solution to the missing empty lines! 
I often manage to pull off relatively advanced stuff like I did here with the merge function but I'm really a newbie when it comes to this language, and scripting/programming in general. I guess I'm kinda crazy for even trying lol. I feel like a mad scientist tinkering with stuff I don't fully understand.
=> Updater for Windows - misc fixes and improvements

updater.bat
Just some more polishing and some changes to prevent some potential issues when the user closes the console window too soon.
I still need @earthlng to test this because the `-updatebatch` switch didn't work for him before and it may be so again.
=> Updater for Windows 3.1

updater.bat
=> Updater for Windows 3.2

updater.bat
You wouldn't believe the things I had to experiment with to finally come up with this new merge function. I really leveled up during the making of this version.
I still marked it as 4.0b because I didn't test it too much, and as always, I'm open to suggestions, etc.
By the way, I always allow edits from maintainers, in case you want to make changes yourselves.
(changes listed in the commit description)
=> Updater for Windows v4.0

prefsCleaner.bat, updater.bat
=> Daily round of tweaks

updater.bat
`/raw/master/` URLs are no longer working on my end. 
That's it.
Yes, really.
(cosmetic shit is a given)
=> Fix updater URLs before someone bitches about it

user.js
I used the short-form for the bugzilla links and added the part-info for tickets with multiple parts. If you don't like it, feel free to change it.
=> move most of the FF59 deprecated/removed prefs

user.js
they're still called System Add-ons: https://firefox-source-docs.mozilla.org/toolkit/mozapps/extensions/addon-manager/SystemAddons.html
Thanks!
=> 0500 System Add-ons

prefsCleaner.bat, updater.bat
Some minor stuff I've been meaning to change for a while. I tried to split the changes into separate commits to make things slightly easier to read. I am now well aware that my history of pull requests is terrible... :hankey: 
Sorry 'bout dat.
=> P*tches for B*tches

updater.bat
I was only testing you, @earthlng! ... Just testing you!
Yeah... right. :rofl:
Oh, the joys of programming...
Summarising, my previous changes made the script compare itself with itself.. Yeah, brilliant. That's why I shouldn't write code when I'm sleepy. It's one of those lessons I never truly learn.
I'm sorry to say I can't properly test this, though, because I keep getting error codes 502 and 503 when I try to download the raw from my fork. But it *should* be OK now.... it *should*!!!
=> fix -updatebatch epic fail

user.js
see https://github.com/ghacksuserjs/ghacks-user.js/issues/439
=> change cookies from block all to allow 1st party

user.js
- scheme: `https://`
- host: `www.lusciousllamas.com`
- port: `:8080`
- path: `/hot/stuff/for/weirdos/gallery.htm`
- query: `?id=weirdo1534&search=fluffy%20and%20wet`
=> scheme+host+path+port -> scheme+host+port+path

README.md, user.js
Closes #546.
To squash, or not to squash, that is the question.
=> Tor-related warnings

user.js
@earthlng review, squash and merge if you're happy. There's probably more, but I'm not making more notes and todo lists, so this is it, a PR
=> 4000: remove old FPI notes

user.js
`https://github.com/pyllyukko/user.js/issues/419`
=> disable System Add-on updates

user.js
@earthlng just squash & merge if you're happy
=> 1700s: revamp Containers header #585

user.js
if you're happy squash & merge
=> 0912: HTTP Auth sub-resources #585

scratchpad-scripts/ghacks-clear-[removed].js, user.js
since 57(?) themes and web extensions are controlled by the same mechanism (301b+302b)
=> remove 0307: themes #648

user.js
source: https://hg.mozilla.org/integration/autoland/rev/2e48b6769911
=> autoplay option "Prompt" was removed in FF66

user.js
=> inactive dead wood, see #710

updater.bat
=> add -RFPalts option

user.js
As I said in #759, this is my PR for pref 0864.
=> Preference 0864

user.js
https://wiki.mozilla.org/Trusted_Recursive_Resolver
=> 0707: Add mode 5

user.js
Add a note for idiots like me they need to debug this one hour.
=> Add NOTE to 2805

user.js
basically revert (+update) https://github.com/ghacksuserjs/ghacks-user.js/commit/c4ec4dbc7780c03aa39b72214d97ba647c47df50
=> about:config warning back to the top + active

user.js
see https://github.com/ghacksuserjs/ghacks-user.js/issues/862
thanks @crssi !
=> 2701: make sure cookieBehavior is always honored

user.js
I don't think we need to get any fancier than that. @earthlng push if you're happy
=> 2031: better reference: closes #1022

updater.sh
- grep -c equals grep | wc -l
- make output prettier
- work with variable instead of temporary file
=> v3.0 - improve readIniFile()

user.js
to match the browserleaks test listed in [1]
=> 1264: update ciphers, fixes #1196

user.js
=> colon insertion

user.js
https://hg.mozilla.org/integration/autoland/rev/b633563955ad
=> proxy direct failover

user.js
=> close #1342
