- user.js
move network.http.sendSecureXSiteReferrer to 9997 and enable a safe alternative for now until we re-work the Referrer-Section
Only merge this after FF52 stable has been released!
> network.http.sendSecureXSiteReferrer

- user.js
Idk if we need/want to add this since it's default true and unlikely ever gonna change.
We have others like this and pyllyukko has tons of those, ie enforcing the default value.
IMO we should add it but I'm open for discussion.
> network.cookie.leave-secure-alone

- user.js
my proposal as a PR, let's have a discussion if necessary and maybe wait with merging this until FF52 stable is released
> signon.autofillForms.http + contextual warning

- user.js
set to 700ms for a slight speedup and to match @atomGit's user.js
> security.dialog_enable_delay

- user.js
Because PB mode still allows the key-commands/menus/context menus/buttons to do both "new window" and "new private window", and because in this mode the PB mode purple mask icon is never shown, this is not clear. See issue #73
> 0001: extra info re starting in PB mode

- user.js
First words of pref number descriptions standardized: using:
enable, disable, set (& one case of reset), start (two of these), enforce, limit, hide, spoof, control
These include items with a prefix such as all of the 1600s: 
/* 1603: CROSS ORIGIN: control when to send a referer [SETUP]
/* 1605: ALL: disable spoofing a referer
This now leaves 37 preferences not starting with those words, and some definitely need work. Will do in a Standardize Part2 PR
Also fixed up `[NOTE] Capitalize first letter..`
Also fixed up numbers `0 = blah` to `0=blah` as per the bulk of them already had no spacing
Other minor changes
Please review in case of any f**kups.
> Standardize Part1 #115

- user.js
https://blocklist.addons.mozilla.org/blocklist/3/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/53.0.3/
... already redirects to ...
https://blocklists.settings.services.mozilla.com/v1/blocklist/3/%7Bec8030f7-c20a-464f-9b0e-13a3a9e97384%7D/53.0.3/
... in FF53.0.3 so we can already commit this FF54 change that uses the direct URL
https://github.com/ghacksuserjs/ghacks-user.js/issues/87#issuecomment-296562854
> extensions.blocklist.url

- user.js
Nits, review syntax etc. Note: 2 items missing deprecation bugzilla tickets, we can get those in time. Note if each section number is made active, the prefs are also - except those which either match the current js (eg TP/SB not active but we do block reporting) or they make no sense or were inactive originally (eg personal 3000 settings etc) - might want to review those choices as well. Also, a few numbers etc changed to match current numbers (eg replaced by items etc, new sections)
> 9999 revamp

- user.js
they are both in TBB 7.0.2.
With .url.override set, media.gmp-manager.url is never used (but let's keep it anyway)
source: https://dxr.mozilla.org/mozilla-central/source/toolkit/modules/GMPInstallManager.jsm#66
Since ESR52 it is not enough anymore to block pinging the GMP update/download server.
There is a local fallback that must be blocked now as well. See: https://bugzilla.mozilla.org/show_bug.cgi?id=1267495.
> 1840 - add override url + disable local fallback

- user.js
moved screenshots up to 0515 and added the FF54 pref. I know I said we can remove that pref but the item needs to be for FF54+ regardless. To make it less confusing I added the pref back in.
> 0515+0516 - screenshots already bundled with FF54

- user.js
the default value in 54 is true. It's not in my OS diff for 54 either so it's true on Linux and Mac as well. I don't think anyone would want to disable this anyway, and we have it as "enable APZ". The linked ghacks article is from 2 years ago and the pref was added before the move to github (no commits for it).
It's old, unnecessary and only wasting space, let's remove it.
> 3009 - remove it

- user.js
- should check if 0360 `user_pref("browser.newtabpage.directory.source", "data:text/plain,");` is still around since the ping pref is gone.
- A bit iffy about 2507 - this spilts two prefs and there's a lot of text. Not sure if FF38+ refers to the second one. We should investigate the still active 2507 and fix that up with some info and version
> FF55+ deprecation

- user.js
makes it even easier for ESR users to re-enable the prefs they still need
> 9999 - JS-comment re-grouping for ESR users

- user.js
it's most likely covered by disabling extensions.formautofill but is nice to know for people who want to enable form-autofill but may want to disable creditCards autofill
> 0517: add .creditCards.enabled;false (FF56+)

- .gitattributes
LF is messing with calls to :message in the updater, at least on my end.
EDIT: Curiously, the updater seems to have CRLF EOL's in the repository, but GitHub still hands out LF versions [here](https://raw.githubusercontent.com/ghacksuserjs/ghacks-user.js/master/updater.bat) and [here](https://github.com/ghacksuserjs/ghacks-user.js/raw/master/updater.bat), which makes me wonder if this can be fixed at all. I guess it ultimately means the `-updatebatch` switch produces unexpected results.
1. Start the updater with `-updatebatch` switch. Let it update itself.
2. Press H in the menu to see the available switches, and you should see CALL errors where the names of the switches would be.
3. Close the updater.
4. Change line endings to CRLF using Notepad++ or the like.
5. Start the updater …
> Convert BAT line-endings to CRLF

- updater.bat
Just very minor changes, mostly adding some missing information. including the changes suggested in https://github.com/ghacksuserjs/ghacks-user.js/issues/283#issuecomment-353766065.
@Thorin-Oakenpants I reply to you here, since I can't post comments on #283 because it says the conversation _"has been locked and limited to collaborators"_ (strange, I know). Your work on the wiki looks good to me. I especially like what you said about hidden prefs in section 3.2, good call!
> Updater for Windows 4.1

- prefsCleaner.bat
- Search string made case-sensitive, because Firefox preferences are.
- The script now uses regex, which allows it to understand `user.js` files formatted using single quotes, spaces and/or tabs in `user_pref` lines.
Trade-off: it can no longer reset preferences that include some special characters in their names. Not an issue for now, just something to remember.
See full discussion [here](https://github.com/ghacksuserjs/ghacks-user.js/pull/321).
> prefsCleaner 1.2

- updater.bat
>  I'm being quoted to introduce something,
>  but I have no idea what it is and certainly
>  don't endorse it.	— [Randall Munroe](https://xkcd.com/1942/)
(sorry, I couldn't help myself)
I believe I gave you folks a decent enough rest from my incessant pull requests, so here I come again.
Just think that the more I bother you now, the less I'll bother you in the future. I mean, if these scripts someday become sentient beings capable of maintaining themselves, and if they are willing to, that will most likely be the last time you'll see me around.
Yes, @earthlng. I know I can't make sentient batch files. It was a joke this time.
- The script doesn't touch the `user.js` file until it really has to.
- The merge function is a bit smarter parsing files, at no significant cost. See examples …
> Updater for Windows v4.3

- user.js
- only recommend extensions as a last resort
- don't need the [NOTE]s for the prefs anymore because it's all explained in the header
- don't need the [SETUP] in the section title itself because the defaults are perfectly fine
- changes to 1606 in preparation for FF59
> 1600 cleanup and header-rewrite

- user.js
These default values are the same in all OSes and all current Firefox versions (ESR, Release, Beta, Nightly). Apart from alerts.showFavicons these defaults are most likely never gonna change
> default values cleanup

- user.js
While I'm at it, I'm changing the 21 instances of
- `[SETTING-56+]` to just `[SETTING]`
- `[SETTING-ESR]` to `[SETTING-ESR52]` because we'll leave those in until 62 (yes I know they may apply to earlier ESRs, but people should be upgraded). Thus no ambiguity with ESR60 vs ESR52 users for the overlap
Note: some [settings] / Options> removed as they no longer exist (did you see they removed the DRM UI option). Double check when you have time (not that they exist, but if I missed anything etc). At some stage I will go thru all these and check them as per the **FF60** interface
> Options> and [settings]

- prefsCleaner.bat
- updater.bat
The most significant change here is that I borrowed my own technique from the merge function in the updater v4 and adapted it to give the prefsCleaner a speed bump. The rest is mostly semantics.
To be honest, I considered rewriting the prefsCleaner in VBScript instead, since it's more straightforward than the updater, but the lack of console output by default still kinda puts me off. So, I just went with this.
It is worth noting that, while it wasn't my goal, with these changes the prefsCleaner should also have better tolerance for special characters within preference names (which counters [the one downside that v1.2 brought along](https://github.com/ghacksuserjs/ghacks-user.js/pull/321#issuecomment-354394222)).
> patches for batch scripts

- prefsCleaner.sh
[Long overdue](https://github.com/ghacksuserjs/ghacks-user.js/issues/340#issuecomment-357446813) port of the prefsCleaner.bat for Unix-like systems. I was bored and had the time for it so.. why not?
This is my very first shell script ever, and I have only tested it with a minimal Cygwin install, so all feedback is very welcome. I did my best aiming for compatibility and reliability but, being a beginner and all, it would surprise me if this couldn't be improved still.
Bear in mind that I couldn't let go of bash-only syntax completely, so this won't work in other shells.
@1xPdd, I hope you're still up for testing.
[Download link](https://raw.githubusercontent.com/claustromaniac/ghacks-user.js/548f0f7e9840de3425bb798127b104bd11298bfc/prefsCleaner.sh) for the lazy ones.
> prefsCleaner.sh (for Linux/Mac)

- updater.bat
supports commenting-out active user-prefs with the merge function.
It needs a line like this in an override file:
```js
// comment-out "security.tls.version.max" = 1202 - wait until FF enables TLS1.3 for everyone by default
```
such a line has to start at column 0 with a double forward-slash followed by a single space, lowercase `comment` `minus` `out`, single space and the prefname in double quotes. Anything after that is optional and can be used for a reminder comment or whatever.
But maybe we should make the format a bit more uncommon, like with 4 slashes or so.
> updater for Windows v4.5

- updater.sh
* updated shebang
* The script now compares its version number to the one online.  If there is a newer version of `updater.sh` online, it is downloaded and run.
* Backup files are now saved to the directory `userjs_backups` instead of causing more bloat in the profile directory.
> Auto update and save backups to folder

- updater.sh
After the discussion on #447 I decided to send single pull requests improving the existent script instead of writing a new one.
This pull request add `wget` as fallback if `curl` is not installed. Why? Because `wget` is often preinstalled on most GNU/Linux distributions, and the end user doesn't need to install a new software for keeping updated the `user.js`.
If you use `wget` or `curl` the behaviour is the same, only the output can change a bit. For example with curl:
```
This script should be run from your Firefox profile directory.
Updating the user.js for Firefox profile:
/home/emanuele/Projects/ghacks-user.js
Your current user.js file for this profile will be backed up and the latest ghacks version from github will take its place.
If currently using the ghacks user.js, please …
```
> Use wget if curl is not available

- user.js
`browser.cache.frecency_experiment` is a dead pref since FF59: https://bugzilla.mozilla.org/1430197
proof: https://dxr.mozilla.org/mozilla-esr60/search?q=frecency_experiment
> move 1007 to 9999

- user.js
- 0301a - do you want to add the `[NOTE] Firefox currently checks every 12 hrs  ...` to `0302a` ? The problem is it also checks for updates every time you open/reload about:preferences and in Menu>Help>About Firefox regardless of when the last check was.
- 0513 - removed because follow-on-search is no longer a deletable system addon
- 2703 - do we just remove `3=for n days` or add a [NOTE] that value 3 was removed in FF63 or something?
- `browser.ctrlTab.recentlyUsedOrder` replaces `browser.ctrlTab.previews` but it now defaults to true. No need to list the new one under 5000 IMO
> removed, renamed or hidden in v63.0

- user.js
Pants said "We do not need to keep anything for ESR users. ESR users are on v60, and we have an archived 60 for them."
This isn't even affecting ESR60 but only older versions.
> remove old information

- updater.sh
This PR focuses on making better use of command line arguments for `updater.sh` using `getopts` as well as adding additional options.
I deleted some past comments and will just update this one to prevent spamming people's emails. 
Result of `./updater.sh -h`:
```txt
Usage: ./updater.sh [-h] [-u] [-d] [-s] [-n] [-b] [-m] [-o OVERRIDE]
Optional Arguments:
-h,		 Show this help message and exit.
-u,		 Update updater.sh and execute silently.  Do not seek confirmation.
-d,		 Do not look for updates to updater.sh.
-s,		 Silently update user.js.  Do not seek confirmation.
-b,		 Only keep one backup of each file.
-o OVERRIDE,	 Filename or path to overrides file (if different than user-overrides.js).
If given a directory, all files inside will be appended recursively.
You can pass multiple files or …
```
> Updater args

- updater.sh
I must not have tested after this change was made:
https://github.com/ghacksuserjs/ghacks-user.js/pull/554#discussion_r236102460
With how it is now, macOS never detects a profile, so I reverted it back and bumped the version number.
> fix profile check

- updater.sh
(This PR should be looked into after #564)
I'm not sure if we want to include this or not, but I thought it might make a nice addition...
From the wiki:
>Several sections in the user.js have one-char switches to enable/disable the entire section (e.g. deprecated items by ESR version). You will have to remember to do these manually if required.
I've added `-e`, which activates the ESR prefs when used.  It matches based on `/* ESR##.x still uses all`, which I think should be specific enough...that phrase would have to stay consistent in future versions of the `user.js` though (I did a quick glance through some old versions and it seems to have stuck around).
> updater.sh: add -e option for ESR users

- user.js
- FF version tags are now square brackets (allows for [FF52-63] etc, as long as you parse for [FF. Any other references to FF versions if needed, use round brackets (e.g in descriptions, header sections etc)
- FF version tags, where possible, are now after each pref. This removes confusion, and allows for extra new prefs to be inserted under that number. The bulk of these were numbered items with a single pref. Where the version tag was in the pref description but we had multiple prefs, I left those mostly alone, because I cannot be sure they all adhere to the same version release. At some stage it would be nice to enforce ALL version tags to each pref (but that would be a lot of work!).
- Default tags are now all `[DEFAULT*]` and can contain extra info, eg [DEFAULT: true in FF61+]. This …
> #574 cleanups

- user.js
The link we had in 0370 is not very useful for end users.
https://abouthome-snippets-service.readthedocs.io/ is better
I did some digging into what exactly snippets are and how it works ...
Snippets = information about mozilla and firefox, like tips + tricks and things they want to highlight or advertise, etc. (~4MB of data with CSS, HTML + JS)
If you want to see the data, load [this](https://snippets.cdn.mozilla.net/5/Firefox/63.0/20181018182531/WINNT_x86_64-msvc/en-US/release/Windows_NT%206.1/default/default/) and look at the response.
"Updates from Mozilla and Firefox", as it says in the UI, doesn't sound that bad but it includes [metrics](https://abouthome-snippets-service.readthedocs.io/en/latest/data_collection.html#metrics), geolocation stuff and runs JS code received from a server …
> move 0370 to 0105b

- user.js
"disable or limit SHA-1 certificates" is about certs, not ciphers.
Because CERTS is 1st in the title I moved it to the 1st item there because it's arguably also the most important of the lot (and renumbered the rest)
We can also drop HSTS from the subgroup title because there's nothing HSTS left atm but I haven't done that yet. Section 1200 header description "Option 1" needs adjustment too but I leave that to you :jeans:
> move 1260 to 122x

- user.js
- don't need these peerconnection prefs other than the main one
- the chance that somebody ends up in WebIDE despite the menu being hidden with .enabled is already slim to none. But if they do then autoinstallADBExtension stops the download of the ADB extension. And even if it didn't - just uninstall it again. NP! the super paranoid and mozilla haters can add the URL in their overrides if they want.
> taking out the garbage

- user.js
@earthlng . now that location bar autocomplete is gone, users will have to resort to css to stop the dropdown. So I see no point anymore in disabling all the suggestion types - because otherwise all you get is a single line blue dropdown.
These three items, 850a, are also on the list in #605 as the ones most often changed - small sample, but seems to be a pattern there. Note: I'm not concerned about any tags right now, the 605 issue can still address that later down the track
This should also solves search engine keywords, right?
What other items should we make inactive here? Which one is the one that shows your search engines as icons on the bottom of the dropdown - that can be make inactive IMO
> location bar changes

- user.js
- telemetry prefs together in 330's
- Firefox Data Collection & Use prefs to 340's (but leave crash reports in 350s)
- move `app.shield.optoutstudies.enabled` to 330's - this is an internal pref which controls if you get the system addon
- make notes that `datareporting.healthreport.uploadEnabled` controls studies and ext recommendations
> clean up "Firefox Data Collection & Use"

- scratchpad-scripts/ghacks-clear-[removed].js
- user.js
Since FF63 you cannot clear cookies by lifetime of days, it is either keep, or clear on shutdown (section 2800), so this pref is now useless. In FF65 they even removed the redundant [SETTING]. Even MOAR reason to remove them.
> removed 2703 + deprecated-2704 #628

- updater.bat
Closes #741
Adds an `-ESR` parameter that, after the `user.js` is downloaded (as `user.js.new`), replaces this line:
```js
/* ESR60.x still uses all the following prefs
```
with this:
```js
// ESR60.x still uses all the following prefs
```
That's all.
> updater.bat -ESR option

- user.js
@earthlng : is this OK?
- sticking the default at the end of the pref line
- I don't quite like the  extra line about TP: it implies the value must be 4 in order to use TP: which is not the case e.g exceptions? And TP is not just cookies, it's also JS (crypto, fingerprint: not 100% sure how it works: I think it just blocks the domains). Or am I overthinking this?
> 2701: cookies default

- user.js
- bye bye http links
- mozillazine is not maintained: lets not use it. Most of these are self-explanatory.
- couldn't find anything decent for ping tracking since it's not an implemented spec: maybe if/when mozilla enable it we can link to something they post
- replaced a few, as good as or better: e.g. the new asm MDN link actually links to the old one in the very first word
- nits, other improvements welcome: e.g: I haven't checked every link still exists or is up to date / still relevant: but I guess that's an ongoing thing
> goodbye http and other stuff

- user.js
- split geo related vs language/locale related
- we could remove the last item in the patch `intl.locale.requested`, or leave it in for info's sake: but I'm not even sure if what I wrote is still correct, and I'd rather not follow it: there's a UI for it
- we could add `privacy.spoof_english` in here as well (inactive)
- because these are active by default, for non en-US bundles we could add something about resetting `2010-2013` - as has been brought up at least three times in issues
- this is a draft, so fixups to typos, better wording etc are welcome
> revamp 0200s

- user.js
https://bugzilla.mozilla.org/1569330
> FF70+: shield studies no longer tied to FHR

- user.js
makes the prefsCleaner scripts useful again for users updating from ESR60 to ESR68
> re-add relevant deprecated items for ESR users

- user.js
https://wiki.mozilla.org/Security:Renegotiation describes
> **the new default behaviour** that was introduced in experimental mozilla-central nightly versions on 2010-02-08
where the last step is
> - should the server (or a MITM) request **renegotiation**, Mozilla will terminate the connection with an error message
and then after talking about breakage ...
> The above defaults may break some client/server environments where a Server is still using old software and requires renegotiation.
mentions workarounds to reduce said breakage:
> In order to give such environments a way to keep using Firefox (et.al.) to connect to their vulnerable server infrastructure, the following preferences are available:
specifically talking about the first 2 prefs listed there, one allowing to specify a list …
> 1201 update

- user.js
- let's not encourage (remove options 1, 2) changing your cipher suite FP
- remove "it's quite technical ..." (everything is technical to someone), trim to one line
- add test link so users can just see that it's FP'able
- reinforce not to fuck with the cipher suite in the cipher's sub-section
> simplify ciphers #839

- user.js
- note: 1403 is a different path: `legacy`
- deprecated is excluded (the section will be cleaned out at EOL for ESR68 anyway)
> update trac tor tickets

- user.js
- adds the new tests including the non-JS JA3
- Stats: the code numbers are from https://dxr.mozilla.org/mozilla-central/source/security/manager/ssl/nsNSSCallbacks.cpp#903
- Telemetry from SSL_CIPHER_SUITE_FULL: 
- go to https://telemetry.mozilla.org/
- click Measurement Dashboard, etc
> update weak ciphers/tests etc, closes #931

- user.js
- `0105e`
- we disable AS, and clearing the default does not stop someone adding their own (it's a different pref) should they chose to use AS
- otherwise, to get rid of the topsites when clicking in an empty urlbar, users have to either know about this pref or enable AS and go manually remove them all
- this is cleaner than disabling topsites with `browser.newtabpage.activity-stream.default.sites` as that actually breaks the functionality (should users want to use AS and topsite suggestions)
- we don't disable topsite suggestions: 0850a: 78+, `browser.urlbar.suggest.topsites` is inactive
- this is the list you see when you click in an empty urlbar, and obviously if you have no topsites then the 0850a pref is rendered useless for suggestions as you type, but doesn't break the …
> various, #959

- user.js
I almost feel as if everyone (myself included) forgot the pref name .. **AfterSearch** and we don't even need to ~~add a note at all~~ mention 0801 at all: it's not about `keyword.enabled` .. it's about searching
> dnsResolveSingleWordsAfterSearch

- user.js
- I split it into two: because regions cover more than just search (and can get future feature creep) - the link says "search and content"
- I don't want to make the search region active, because that might create problems for non en-US users .. or indeed, for any users not in en-US region
- I do not know how this affects new profiles: does the region ever get set? in en-US I **think** it's the default, but what about others (how quick is it set after a new profile is created?)
- does `browser.region.update.enabled` need a version number?  I don't think we need bother with a hidden tag since it's no longer hidden in 80, but I don't know when it was added and when it was made functional: maybe it's best to just tag it as `[FF80+]`
- if we do that we should change the `0207` order to …
> 0207/0208: region/search

- user.js
If you want we could add a line that explains that the prefs weren't removed until 82 to make it easier for people to understand without looking at the bugzillas. ESR68 is almost EOL, so I don't think we're going to get people asking why the pref still exists but we said it was "deprecated"
> 2201 deprecated (dead prefs removed in 82), #979

- updater.sh
* merge two declarations of download command into one
* add max-redirects to prevent redirect loops
* add silent options (prettier than `> /dev/null`)
* shorten `download_file ()`
* exit instead of continue with a "non-file", which can lead to unwanted behavior
* open_file(): pipe instead of nested sub-shell
* readIniFile(): `grep -c` equals `grep | wc -l`
* make output prettier
* work with variable instead of temporary file
* update `PROFILE_PATH` more directly
> Updater.sh rework 2

- user.js
- less active prefs
- now that ESR68 is EOL, at least a whopping two (0602, 1273)
- also I don't know when the default changed - another whopping whole one (1240)
- and where we do enforce/reset a pref to default, lets say that
- this is not a definitive list, sing out if there is anything else
- IPv6 info
- especially for Iron Heart who likes to claim that this pref breaks 5% of sites
- cleanup of settings tags now we only care abut ESR78+
> miscellaneous

- user.js
- make 1401 inactive: it affects RFP's FPing
- remove old warning/setup-web: we do not care about documenting breakage or FPing risks when we have a warning and they are inactive. If someone uses them, that's on them
- new warnings
> fixup font prefs vs RFP, see #1025

- scratchpad-scripts/arkenfox-clear-removed.js
- user.js
Also remove the redundant "isolate" in all the tickets. Get rid of the double asterisks (less noisy) and change indent to similar to RFP: note 4000 + 4500 section description indents are different to all the others, but they're also sort of special case
> remove 4003: partition, see #1051

- updater.sh
Patched the `update_updater` function to use the script's real filename instead of `${SCRIPT_DIR}/updater.sh`.
This allows renaming the script to custom names, such as `update-userjs.sh`
> updater.sh: support custom script names

- user.js
- don't differentiate between channels
- both can be made inactive
- webcompat requires user action: and I don't see this as a bad thing to have in non-stable
- unsubmitted crashReports on Nightly is probably already covered by killing the URL, so no big deal
> tweak defaults

- user.js
This is a draft
- merge 4700's into 4600s
- remove old numbers in the square brackets
- remove notation of when RFP kicked in (that info is in 4500s)
- since we now do not recommend this section
- cleanup info on each release in README section
- do away with one char flip
- move 4616 to deprecated where it belongs
- remove "optional if..." lines
- start cleaning up references, descriptions to shorten the section
- will list what I removed: e.g. bugzillas to when the pref was added are a bit useless
todo / consider
- 4600 title
- 4600 section description can be a lot better
- 4600 link to wiki page on RFP ( issue #1218 - that is, if RFP is not for you, then just use Canvas Blocker, which can leak but should fool naive scripts if any get thru etc )
- do we want to add …
> change 4600s into do not use, #1221

- prefsCleaner.sh
#1255 Provided an incomplete fix for old shell syntax, where " quotes previously needed to be specially escaped in \` ... \` syntax but no longer need to be escaped in $( ... ) syntax.
> prefsCleaner.sh: Fix invalid regular expression

- user.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1666725
> update 0704: GIO, closes #1050

- updater.sh
I was having an issue using the updater.sh script on my Ubuntu 20.04 machine.
After some investigation I found at that the `download_file` function returns the path to the temporary file with a leading newline, which was produced by the curl command.
That resulted in error messages and the script not being able to determine the available version, e.g.:
```
sed: can't read 
/tmp/tmp.RBrbSv40X0: No such file or directory
Please observe the following information:
Firefox profile:  <redacted>
Available online: Not detected.
Currently using:  * version: 97
```
The simple change in this PR fixed the problem for me and should not cause any side effects even on systems where this problem might not occur right now.
> Fix newline issue when downloading files in updater.sh

- updater.sh
Hello user.js folks! 👋 Long time listener, first time caller here.
I recently used the `updater.sh` script to update one of my profiles, but I fat-fingered my reply to the confirmation prompt with a `T` instead of a `Y`, and it proceeded to update anyway. This seems bad! Confirmation prompts like this should err on the side of caution and only perform a destructive operation if the user explicitly enters an affirmative `Y`/`y` response. (Yes, I'm aware that the script makes a backup file, but still…)
I dug into the code and realized that you're doing the opposite: `updater.sh` only aborts upon receiving a `N`/`n` response. *Any* other input appears to be treated as a destructive `Y`/`y`. Yikes!
So, I swapped the logic around. It now treats only `Y`/`y` as an affirmative response.
Tested …
> make updater.sh check explicitly for Y/y instead of N/n

- prefsCleaner.sh
`updater.sh` creates a `userjs_backups` directory and `user.js` backups are saved to it:
https://github.com/arkenfox/user.js/blob/996881aef184246a011ac29382e91d634cda7b65/updater.sh#L270-L273
Thought it would be nice to have the same behavior with `prefsCleaner.sh`, it unclutters the Firefox profile directory.
> Back up prefs.js to `prefsjs_backups` directory

- prefsCleaner.sh
Running`prefsCleaner.sh` prompts the user for command selection before continuing. However, it fails to tell the user how to proceed and instead just displays the following options:
`1) Start
2) Help
3) Exit`
Common sense would dictate that the user should enter one of the commands to proceed, but the script only accepts the numerical input. For example `Start` and `start` fail to resume the script, but `1` does.
After a few tries, the user should be able to figure out how to proceed, but appending this short line (or equivalent) increases usability, specifically for inexperienced users. It's not a huge improvement, but it's a small improvement in clarity that could save a few keystrokes.
> Improve Usability by Clarifying Desired Action

- prefsCleaner.bat
- updater.bat
Currently, in the .bat files, the date and time used for renaming backup copies of files are formatted in a way that is locale dependent.  For example, in my locale calling
```cmd
echo %date%_%time%
```
outputs `sre. 09. 11. 2022_13:07:47,71`.
This does not sort nicely and in addition includes unneeded information, such as the weekday and the hundredths of second.
In this pull request, I explicitly requested the format of date and time, which translates into consistent filenames of backup files. I used [the method suggested by an answer on StackOverflow](https://stackoverflow.com/a/203116/4341436). The format was chosen to mirror `updater.sh` , while I also included the ISO format as an alternative in a remark.
I also bumped the version of the `updater.bat` (but not `prefsCleaner.bat`) …
> Format date and time consistently.

- prefsCleaner.bat
Usage:
prefsCleaner.bat -unattended
Skips the prompt for user input and proceeds when -unattended is specified. If omitted, default behaviour is unchanged.
Code taken from updater.bat for consistency.
Please review this PR closely as I'm not fluent in batch scripting. The revised script appears to function properly with and without -unattended, but I'm not aware of common pitfalls.
Signed-off-by: Keith Harrison <keithh@protonmail.com>
> prefsCleaner.bat: add -unattended flag

- prefsCleaner.sh
- updater.sh
Check if running as root and if any files have the owner/group as root|wheel. Abort on both.
Should (hopefully) prevent stuff like: https://github.com/arkenfox/user.js/issues/1587
Discussion: https://github.com/arkenfox/user.js/pull/1595
This does not attempt to correct the permissions, just notify the user
and abort.
If I followed https://github.com/arkenfox/user.js/issues/1587 right.
The original person didn't realize that it appended and subsequent
people tried to run with elevated privileges.  This should at least fix
the second.
> updater.sh/prefsCleaner.sh: Check for root and abort

- updater.sh
Sorry to add yet another updater.sh PR to the pile, this should get rid of the syntax error from #1667
> Fix escape character/syntax error in updater.sh
